import { StyleSheet } from "react-native";
import { FONT_FAMILY } from "../theme/fonts";
import { typography } from "../theme/typography";
import { shadowStyle } from "../theme/shadow";
import { colors } from "../theme/colors";

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: colors.surface.neutral,
    paddingHorizontal: 16,
    paddingTop: 24,
  },
  center: {
    flex: 1,
    backgroundColor: colors.surface.neutral,
    justifyContent: "center",
    alignItems: "center",
  },
  centerText: {
    ...typography.textRegular,
    marginTop: 12,
    fontSize: 14,
    color: colors.text.dim,
  },
  card: {
    backgroundColor: colors.surface.screen,
    borderRadius: 20,
    padding: 20,
    ...(shadowStyle({
      boxShadow: "0px 6px 12px rgba(0,0,0,0.06)",
      shadowColor: colors.overlay.shadow,
      shadowOpacity: 0.06,
      shadowRadius: 12,
      shadowOffset: { width: 0, height: 6 },
      elevation: 4,
    }) as object),
    marginBottom: 16,
    alignItems: "center",
  },
  lockEmoji: {
    fontSize: 32,
    marginBottom: 8,
  },
  cardTitle: {
    ...typography.title,
    fontSize: 22,
    fontWeight: "700",
    color: colors.text.primary,
    textAlign: "center",
    marginTop: 4,
  },
  cardSubtitle: {
    ...typography.textRegular,
    fontSize: 13,
    color: colors.text.dim,
    textAlign: "center",
    marginTop: 8,
    lineHeight: 18,
  },
  primaryButton: {
    marginTop: 20,
    alignSelf: "stretch",
    backgroundColor: colors.brand.primary,
    borderRadius: 14,
    paddingVertical: 12,
    alignItems: "center",
  },
  primaryButtonText: {
    color: colors.text.inverse,
    fontSize: 16,
    fontWeight: "600",
    fontFamily: FONT_FAMILY.regular,
  },
  secondaryButton: {
    marginTop: 10,
    alignSelf: "stretch",
    borderRadius: 14,
    paddingVertical: 12,
    alignItems: "center",
    borderWidth: 1,
    borderColor: colors.border.strong,
    backgroundColor: colors.surface.screen,
  },
  secondaryButtonText: {
    color: colors.brand.primary,
    fontSize: 16,
    fontWeight: "600",
    fontFamily: FONT_FAMILY.regular,
  },
  pickerScreen: {
    flex: 1,
    backgroundColor: colors.surface.neutral,
  },
  pickerContent: {
    paddingTop: 10,
  },
  sectionTitle: {
    ...typography.title,
    marginTop: 18,
    marginHorizontal: 16,
    fontSize: 18,
    fontWeight: "800",
    color: colors.text.primary,
  },
  reportCard: {
    marginTop: 12,
    marginHorizontal: 16,
    backgroundColor: colors.surface.screen,
    borderRadius: 18,
    overflow: "hidden",
  },
  reportImageWrap: {
    position: "relative",
    backgroundColor: colors.icon.placeholder,
  },
  reportImagePlaceholder: {
    height: 160,
    width: "100%",
  },
  mileageBadge: {
    position: "absolute",
    right: 10,
    bottom: 10,
    backgroundColor: colors.brand.primary,
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  mileageBadgeText: {
    color: colors.text.inverse,
    fontSize: 10,
    fontWeight: "600",
    fontFamily: FONT_FAMILY.regular,
  },
  reportBody: {
    padding: 14,
    gap: 6,
  },
  reportPrice: {
    ...typography.title,
    fontSize: 18,
    fontWeight: "800",
    color: colors.text.primary,
  },
  reportSub: {
    ...typography.textRegular,
    fontSize: 12,
    color: colors.text.faint,
  },
  openButton: {
    marginTop: 8,
    backgroundColor: colors.brand.primary,
    borderRadius: 14,
    paddingVertical: 10,
    alignItems: "center",
  },
  openButtonText: {
    color: colors.text.inverse,
    fontWeight: "700",
    fontSize: 14,
    fontFamily: FONT_FAMILY.regular,
  },
  fab: {
    position: "absolute",
    right: 18,
    bottom: 96,
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: colors.brand.primary,
    alignItems: "center",
    justifyContent: "center",
    ...(shadowStyle({
      boxShadow: "0px 8px 12px rgba(0,0,0,0.15)",
      shadowColor: colors.overlay.shadow,
      shadowOpacity: 0.15,
      shadowRadius: 12,
      shadowOffset: { width: 0, height: 8 },
      elevation: 6,
    }) as object),
  },
  fabPlus: {
    color: colors.text.inverse,
    fontSize: 30,
    fontWeight: "700",
    marginTop: -2,
    fontFamily: FONT_FAMILY.regular,
  },
});

