import { StyleSheet } from "react-native";
import { FONT_FAMILY } from "../../shared/theme/fonts";
import { typography } from "../../shared/theme/typography";

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: "#F7F7F7",
    paddingHorizontal: 16,
    paddingTop: 24,
  },
  center: {
    flex: 1,
    backgroundColor: "#F7F7F7",
    justifyContent: "center",
    alignItems: "center",
  },
  centerText: {
    ...typography.textRegular,
    marginTop: 12,
    fontSize: 14,
    color: "#555",
  },
  card: {
    backgroundColor: "#FFFFFF",
    borderRadius: 20,
    padding: 20,
    shadowColor: "#000000",
    shadowOpacity: 0.06,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 6 },
    elevation: 4,
    marginBottom: 16,
    alignItems: "center",
  },
  lockEmoji: {
    fontSize: 32,
    marginBottom: 8,
  },
  cardTitle: {
    ...typography.title,
    fontSize: 22,
    fontWeight: "700",
    color: "#1E1E1E",
    textAlign: "center",
    marginTop: 4,
  },
  cardSubtitle: {
    ...typography.textRegular,
    fontSize: 13,
    color: "#555",
    textAlign: "center",
    marginTop: 8,
    lineHeight: 18,
  },
  primaryButton: {
    marginTop: 20,
    alignSelf: "stretch",
    backgroundColor: "#DB4431",
    borderRadius: 14,
    paddingVertical: 12,
    alignItems: "center",
  },
  primaryButtonText: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "600",
    fontFamily: FONT_FAMILY.button,
  },
  secondaryButton: {
    marginTop: 10,
    alignSelf: "stretch",
    borderRadius: 14,
    paddingVertical: 12,
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#DB4431",
    backgroundColor: "#FFFFFF",
  },
  secondaryButtonText: {
    color: "#DB4431",
    fontSize: 16,
    fontWeight: "600",
    fontFamily: FONT_FAMILY.button,
  },
  pickerScreen: {
    flex: 1,
    backgroundColor: "#F7F7F7",
  },
  pickerContent: {
    paddingTop: 10,
  },
  sectionTitle: {
    ...typography.title,
    marginTop: 18,
    marginHorizontal: 16,
    fontSize: 18,
    fontWeight: "800",
    color: "#1E1E1E",
  },
  reportCard: {
    marginTop: 12,
    marginHorizontal: 16,
    backgroundColor: "#FFFFFF",
    borderRadius: 18,
    overflow: "hidden",
  },
  reportImageWrap: {
    position: "relative",
    backgroundColor: "#EEE",
  },
  reportImagePlaceholder: {
    height: 160,
    width: "100%",
  },
  mileageBadge: {
    position: "absolute",
    right: 10,
    bottom: 10,
    backgroundColor: "#DB4431",
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  mileageBadgeText: {
    color: "#FFFFFF",
    fontSize: 10,
    fontWeight: "600",
    fontFamily: FONT_FAMILY.regular,
  },
  reportBody: {
    padding: 14,
    gap: 6,
  },
  reportPrice: {
    ...typography.title,
    fontSize: 18,
    fontWeight: "800",
    color: "#1E1E1E",
  },
  reportSub: {
    ...typography.textRegular,
    fontSize: 12,
    color: "#777",
  },
  openButton: {
    marginTop: 8,
    backgroundColor: "#DB4431",
    borderRadius: 14,
    paddingVertical: 10,
    alignItems: "center",
  },
  openButtonText: {
    color: "#FFFFFF",
    fontWeight: "700",
    fontSize: 14,
    fontFamily: FONT_FAMILY.button,
  },
  fab: {
    position: "absolute",
    right: 18,
    bottom: 96,
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: "#DB4431",
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#000",
    shadowOpacity: 0.15,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 8 },
    elevation: 6,
  },
  fabPlus: {
    color: "#FFFFFF",
    fontSize: 30,
    fontWeight: "700",
    marginTop: -2,
    fontFamily: FONT_FAMILY.button,
  },
});
